
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "http://hoangmaihuy.github.io"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

#baseurl: /

# Google tracking id

google-tracking-id: "UA-83041909-3"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Mai Huy Hoàng"
title: "{ Mei Brilliant }"
description: "Ever tried. Ever failed. No matter. Try Again. Fail again. Fail better."
keywords: "hoang, hoangmaihuy, personal, jekyll, theme"
favicon: "/img/favicon/favicon.ico"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"

background-img: "../img/Orbit.png"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: False # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "I love it when you just don't care"
  - text: "I love it when you dance like there's nobody there"
  - text: "So when it gets hard, don't be afraid"
  - text: "We don't care what them people say"
  - text: "I love it when you don't take no"
  - text: "I love it when you do what you want cause you just said so"
  - text: "Let them all go home, we out late"
  - text: "We don't care what them people say"
  - text: "We don't have to be ordinary"
  - text: "Make your best mistakes"
  - text: "'Cause we don't have the time to be sorry"
  - text: "So baby be the life of the party"
  - text: "I'm telling you to take your shot it might be scary"
  - text: "Hearts are gonna break"
  - text: "'Cause we don't have the time to be sorry"
  - text: "So baby be the life of the party"
  - text: "Together we can just let go"
  - text: "Pretending like there's no one else here that we know"
  - text: "Slow dance fall in love as the club track plays"
  - text: "We don't care what them people say"
  - text: "We don't have to be ordinary"
  - text: "Make your best mistakes"
  - text: "'Cause we don't have the time to be sorry"
  - text: "So baby be the life of the party"
  - text: "I'm telling you to take your shot it might be scary"
  - text: "Hearts are gonna break"
  - text: "'Cause we don't have the time to be sorry"
  - text: "So baby be the life of the party"

me-img: "/img/profile.jpg"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/favicon/android-icon-36x36.png"
icon-48p: "/img/favicon/android-icon-48x48.png"
icon-72p: "/img/favicon/android-icon-72x72.png"
icon-96p: "/img/favicon/android-icon-96x96.png"
icon-144p: "/img/favicon/android-icon-144x144.png"
icon-192p: "/img/favicon/android-icon-192x192.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 84

paginate: 5

email-share: True
fb-share: True
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: False
pocket-share: False
vkontakte-share: False

disqus-shortname: "hoangmaihuy"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/infinity.png"
    date: "To Infinity & Beyond"
    description: "Trying to save the world with coffee and keyboard"
  - image: "/img/timeline/tju.png"
    date: "Sep 2016 - Jun 2017"
    description: "Tianjin University, Chinese Language"
  - image: "/img/timeline/uet.png"
    date: "Sep 2015 - Jun 2016"
    description: "University of Engineering and Technology - VNU, Computer Science"
  - image: "/img/timeline/tpc.png"
    date: "Sep 2012 - Jun 2015"
    description: "Tran Phu High School for Gifted Students, Started coding"
  - image: "/img/timeline/profile.jpg"
    date: "Oct 21, 1997"
    description: "Superhero reborn!"

# First image of the Timeline

timeline-img: "/img/timeline/spidertocat.png"

###########
# Contact #
###########

email: "maihuyhoang97@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "I'm perfectly happy with all the people who are walking around and just staring at the clouds and looking at stars and saying &quot;I want to go there&quot;. But I'm looking at the ground, and I want to fix the pothole that's right in front of me before I fall in. This is the kind of person I am."
author_blurb_image: "/img/me.jpg"

##################
# Social Buttons #
##################

social:
  - title: "facebook"
    url: "https://facebook.com/huyhoang.chuyentin"
  - title: "instagram"
    url: "https://instagram.com/hoangmaihuy"
  - title: "github"
    url: "https://github.com/hoangmaihuy"
  - title: "linkedin"
    url: "https://linkedin.com/in/hoangmaihuy"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: hoangmaihuy
keybase-in-social: False
keybase-in-footer: False

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag
  - jekyll-mentions
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-feed
